name: RasterToNetwork
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - numpy=1.24.4
  - scipy=1.10.1
  - networkx=3.1
  - geopandas=0.13.2
  - fiona=1.9.6
  - shapely=2.0.7
  - rasterio=1.2.10
  - scikit-image=0.21.0
  - pyogrio=0.7.2
  - pyproj=3.5.0
  - gdal=3.0.2
  - ipykernel=6.29.2
  - pip=23.3.2
  - pip:
      - sknw==0.15
